create schema if not exists tempdb;
set search_path to tempdb;

create domain tempdb.multiocc as text;

drop table if exists
  Data,
  thes
cascade;

create table Data (
  RecordNumber varchar(5) not null,
  InternalMemo multiocc null,
  Comments text null,
  RecNum varchar(7) not null check(left(RecNum, 3) = 'WRN'),
  Org1 varchar(100) null,
  Org2 varchar(70) null,
  Org3 varchar(70) null,
  Org4 varchar(70) null,
  Org5 varchar(70) null,
  AltOrg multiocc null,
  FormerOrg multiocc null,
  XRef multiocc null,
  StreetBuilding varchar(90) null,
  StreetAddress varchar(90) null,
  StreetCity varchar(40) null,
  MailCareOf varchar(60) null,
  Building varchar(90) null,
  Address  varchar(90) null,
  City varchar(40) null,
  Province varchar(25) null,
  PostalCode varchar(7) null,
  Accessibility multiocc null,
  Location varchar(60) null,
  Intersection varchar(60) null,
  OfficePhone multiocc null,
  Fax multiocc null,
  EMail multiocc null,
  WWW varchar(255) null,
  AfterHoursPhone multiocc null,
  CrisisPhone multiocc null,
  TDDPhone multiocc null,
  Data varchar(30) null,
  Description multiocc null,
  PubDescription text null,
  GeneralInfo text null,
  BND multiocc null,
  OtherResource text null,
  Fees text null,
  Hours text null,
  Dates text null,
  AreaServed multiocc null,
  Eligibility text null,
  Application multiocc null,
  Languages multiocc null,
  Contact1 varchar(60) null,
  Contact1Title varchar(120) null,
  Contact1Org varchar(90) null,
  Contact1Phone multiocc null,
  Contact2 varchar(60) null,
  Contact2Title varchar(120) null,
  PrintedMaterial multiocc null,
  Contact2Org varchar(90) null,
  Contact2Phone multiocc null,
  Contact3 varchar(60) null,
  Contact3Title varchar(120) null,
  Contact3Org varchar(90) null,
  Contact3Phone multiocc null,
  Contact4 varchar(60) null,
  Contact4Title varchar(120) null,
  Contact4Org varchar(90) null,
  Contact4Phone multiocc null,
  DateEstablished varchar(60) null,
  Elections varchar(120) null,
  Funding multiocc null,
  DDCode varchar(10) null,
  LevelOfService varchar(60) null,
  Subject multiocc null,
  UsedFor multiocc null,
  Blue multiocc null,
  SeeAlso multiocc null,
  LocalSubjects multiocc null,
  TypeOfRecord varchar(2) null,
  QualityLevel varchar(20) null,
  ToBeDeleted varchar(20) null,
  Distribution multiocc null,
  Pub multiocc null,
  SourceOfInfo varchar(60) null,
  SourceTitle varchar(60) null,
  SourceOrg varchar(60) null,
  SourceBuilding varchar(30) null,
  SourceAddress varchar(60) null,
  SourceCity varchar(30) null,
  SourceProvince varchar(2) null,
  SourcePostalCode varchar(7) null,
  SourcePhone multiocc null,
  CollectedBy varchar(40) null,
  DateCollected varchar(10) null,
  CreatedBy varchar(40) null,
  UpdatedBy varchar(40) null,
  UpdateDate varchar(10) null,
  UpdateSchedule varchar(10) null,
  HistoryOfUpdate varchar(10) null,
  LastModified multiocc null,
  org1_sort varchar(100) null,
  id serial primary key,
  org_name_id integer not null
);

copy data from '/home/todd/git/reload/unload/172.dat' csv quote '''' encoding 'WIN1252';


